apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: webapp-config-map
  restartPolicy: Never
